# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Push on Master - Build and Deploy Node.js app to Azure Web App

on:
  push:
    branches:
      - master
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: npm install and build client
      run: |
        cd client
        npm install
        npm run build

    - name: npm install server
      run: |
        cd playitback
        npm install

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'playitback'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_02363fd58dc941b688ed15395852b1ad }}
        package: .